spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: agcim
    password: agcim123
    url: jdbc:postgresql://192.168.4.35:5432/test_file
    driver-class-name: org.postgresql.Driver

server:
  port: 10000

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: true
      logic-not-delete-value: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


minio:
  accessKey: "admin"
  secretKey: "12345678"
  url: "http://127.0.0.1:9000/"
